server.servlet.context-path=/DemoBackEnd
server.port=9595
#Configuracion de JPA
spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#Configuracion de DataSource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://127.0.0.1:5434/demodb_dev
spring.datasource.username=postgres_user_dev
spring.datasource.password=clave_user_dev
#Para 404 URL
spring.mvc.throw-exception-if-no-handler-found=true
spring.mvc.static-path-pattern=/templates

